# Generated by Django 3.2.4 on 2021-09-20 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Teachers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherslist',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teachers_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
