# Generated by Django 3.2.4 on 2021-08-09 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Teachers_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherslist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacherslist',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacherslist',
            name='last_name',
        ),
        migrations.AddField(
            model_name='teacherslist',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
