# Generated by Django 3.2.4 on 2021-08-09 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers_app', '0003_alter_teacherslist_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherslist',
            old_name='userID',
            new_name='userId',
        ),
    ]
