# Generated by Django 3.2.4 on 2021-08-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers_app', '0004_rename_userid_teacherslist_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherslist',
            name='teacher',
            field=models.BooleanField(default=True),
        ),
    ]
