# Generated by Django 3.2.4 on 2021-09-20 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers_app', '0002_alter_teacherslist_userid'),
        ('Admin_panel', '0002_offeredcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField(default=1, null=True)),
                ('section', models.CharField(default='A', max_length=4, null=True)),
                ('assignTeacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers_app.teacherslist')),
            ],
        ),
    ]
