# Generated by Django 3.2.4 on 2021-08-08 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MarksDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_1', models.IntegerField()),
                ('quiz_2', models.IntegerField()),
                ('quiz_3', models.IntegerField()),
                ('Assignment', models.IntegerField()),
                ('presentation', models.IntegerField()),
                ('mid', models.IntegerField()),
                ('final', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students_app.students')),
            ],
        ),
    ]
