# Generated by Django 3.2.4 on 2021-08-09 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers_app', '0003_alter_teacherslist_userid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accademic_details', '0001_initial'),
        ('Students_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksdistribution',
            name='mid_improvement',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marksdistribution',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Teachers_app.teacherslist'),
        ),
        migrations.AddField(
            model_name='students',
            name='userId',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=40)),
                ('mother_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students_app.students')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registeredCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accademic_details.course')),
                ('registeredSemester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accademic_details.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students_app.students')),
            ],
        ),
    ]
