# Generated by Django 3.2.4 on 2021-09-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(default='Anonymous', max_length=70)),
                ('header', models.CharField(max_length=500)),
            ],
        ),
    ]
