# Generated by Django 3.2.4 on 2021-08-09 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Teachers_app', '0004_rename_userid_teacherslist_userid'),
        ('Students_app', '0002_auto_20210809_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksdistribution',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers_app.teacherslist'),
        ),
        migrations.AlterField(
            model_name='students',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
