# Generated by Django 3.2.4 on 2021-08-09 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers_app', '0001_initial'),
        ('Students_app', '0002_studentsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksdistribution',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Teachers_app.teacherslist'),
        ),
    ]
