# Generated by Django 3.2.4 on 2021-08-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students_app', '0003_auto_20210809_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student',
            field=models.BooleanField(default=True),
        ),
    ]
