# Generated by Django 3.2.4 on 2021-08-10 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Students_app', '0004_students_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsinfo',
            name='sid',
        ),
        migrations.AddField(
            model_name='studentsinfo',
            name='student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentsinfo',
            name='studentID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentsinfo',
            name='userId',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marksdistribution',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students_app.studentsinfo'),
        ),
        migrations.AlterField(
            model_name='registeredcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students_app.studentsinfo'),
        ),
        migrations.AlterField(
            model_name='studentsinfo',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentsinfo',
            name='father_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='studentsinfo',
            name='mother_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='studentsinfo',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
