# Generated by Django 3.2.4 on 2021-08-10 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Students_app', '0005_auto_20210810_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsinfo',
            name='studentID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentsinfo',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
