# Generated by Django 3.2.4 on 2021-09-20 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students_app', '0005_auto_20210921_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksdistribution',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students_app.studentsinfo'),
        ),
    ]
