# Generated by Django 3.2.4 on 2021-09-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students_app', '0006_alter_marksdistribution_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksdistribution',
            name='teacher',
        ),
    ]
