# Generated by Django 3.2.4 on 2021-09-20 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_panel', '0003_batchinfo'),
        ('Students_app', '0007_remove_marksdistribution_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsinfo',
            name='batchId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='batch_info', to='Admin_panel.batchinfo'),
        ),
    ]
